#!/bin/bash

DBFILE="sjsmusic.db"

WHERE=""
case "$1" in
    '-n') WHERE='balance < 0';;
    '-p') WHERE='balance > 0';;
    '-z') WHERE='balance = 0';;
    '-e') WHERE='balance < -5';;
esac

if [ -z "$WHERE" ]
then
    WHERE="where";
else
    WHERE="where $WHERE and";
fi

ORDER="order by name"
case "$2" in
    '-i') ORDER='order by momefid';;
    '-b') ORDER='order by balance';;
    '-n') ORDER='order by name';;
esac

if [ "$3" = '-r' ]
then
    ORDER="$ORDER desc";
fi

sqlite3 $DBFILE << EOS
.mode column
.headers on
select momefid, name, substr('          ', 0, 10 - length(printf('%.2f', balance))) || printf('%.2f', balance) as balance from balance $WHERE momefid in (select momefid from active_family) $ORDER;
.print
select count(*) as families, sum(balance) as total from balance $WHERE momefid in (select momefid from active_family);
EOS
