#!/bin/bash

for f in `find lib/ -name '*.pm' | sort`; do carton run perl -c $f; done;
for f in `find scripts/ -type f -and -not -path "*/\.*" -and -not -name "carton-runner" | sort`; do carton run perl -c $f; done;
