#!/bin/bash

sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select type, count(amount) as count, sum(amount) as total from payments where deposited is null and type in ('cash', 'paypal') group by type order by type desc;
.headers off
select 'check' as type, count(amount) as count, sum(amount) as total from payments where deposited is null and type like 'check%';
select 'deposit' as type, count(amount) as count, sum(amount) as total from payments where deposited is null and type != 'paypal' and type != 'adjustment';
EOS

echo ""
echo ""

sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select last_name, type as "check no", amount from payments join parents on parents.email = payments.email where deposited is null and type like 'check%';
EOS
