#!/bin/bash

ID=$1
DBFILE='sjsmusic.db'
CLIENT='sqlite3'

RUN="$CLIENT $DBFILE"
PRE='-header -html'

echo "<HTML>
<HEAD>
    <style>
        body {
            background: white;
        }
        table {
            padding: 8px;
        }
        table th {
            text-align: left;
            text-decoration: underline;
        }
        table.payment tr:nth-child(odd) td{
            background-color: #AAAAAA;   /* gray */
            color: black;
        }
        table.payment tr:nth-child(even) td{
            background-color: #DDDDDD;   /* silver */
            color: black;
        }
        table.payment tr td:nth-child(3){
            text-align: right;
        }
        table.payment tr:last-child{
            font-weight: bold;
        }
        td {
            padding: 2px;
        }
    </style>
</HEAD>
<BODY>
<TABLE>"
$RUN $PRE "select
                f.name as Family,
                '$' || printf('%.2f', f.tuition) as Tuition,
                p1.o as 'Payment Plan'
            from family as f, prettify as p1
            where f.momefid = $ID and
            (p1.type = 'plan' and p1.i = f.plan);"
echo "</TABLE>
<TABLE>"
$RUN $PRE "select
            p.firstname || ' ' || p.lastname as 'Student Name',
            p.grade as Grade,
            cm.class as Class,
            cm.instrument as Instrument,
            d.name as Day
        from person as p, class_member as cm, days_of_week as d
        where p.id = cm.personid and
        p.id in (select personid from family_member where momefid = $ID)
        and d.id = cm.day
        order by firstname;"
echo "</TABLE>
<TABLE class=\"payment\">"
$RUN $PRE << EOS
        select l.id as 'Transaction ID',
            l.date as Date,
            printf('%.2f', l.amount) as Amount,
            p1.o as 'Transaction Type',
            l.checknum as 'Check Num',
            l.notes as Notes
        from ledger as l, prettify as p1
        where momefid = $ID and
        (p1.type = 'ledger' and p1.i = l.type)
        order by l.id;
EOS
$RUN -html "select
    ' ', 'Balance' , printf('%.2f', balance) as Balance 
    from balance where momefid = $ID;"
echo "</TABLE>
</BODY>
</HTML>"
