#!/bin/bash

NAME=$1
EXEC="statement"

if [ "$NAME" = "-h" ]
    then
        NAME=$2
        EXEC="html-statement"
fi

MOMEFID=`./query -noheader -list "select distinct(momefid), name from active_family where momefid in (select momefid from active_person where lastname like '%${NAME}%' or firstname like '%${NAME}%');" | menupick -1`

./$EXEC `echo ${MOMEFID} | f 0 "\|"`
