#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No MOMEFID supplied"
    echo "$0 <MOMEFID>"
    exit
fi

ID=$1
DBFILE='sjsmusic.db'
CLIENT='sqlite3'

RUN="$CLIENT $DBFILE"
PRE='-header -html'

echo "<HTML>
<HEAD>
    <style>
        body {
            background: white;
            font-size: 100%;
            font-family: Arial, sans-serif;
        }
        table {
            border-spacing: 4px;
        }
        th {
            text-align: left;
            text-decoration: underline;
        }
        table.payment tr:nth-child(odd) td {
            background-color: #AAAAAA;   /* gray */
            color: black;
        }
        table.payment tr:nth-child(even) td {
            background-color: #DDDDDD;   /* silver */
            color: black;
        }
        table.payment tr td:nth-child(2) {
            text-align: right;
        }
        table.payment tr:last-child {
            font-weight: bold;
        }
        table.payoff td {
            background-color: #DDDDDD;  /* silver */
            color: black;
            font-weight: bold;
        }
        td {
            cellspacing: 4px;
        }
        .head1 {
            font-size: 2em;
        }
        .head2 {
            font-size: 1.5em;
        }
    </style>
</HEAD>
<BODY>
<DIV class="heading">
<SPAN class="head1">Mrs. O'Leary's Music Education</SPAN>
<BR>
<SPAN class="head2">Family Financial Statement</SPAN>
<BR><BR>
</DIV>
<TABLE class="family info">"
$RUN $PRE "select
                f.name as 'Family Name',
                '$' || printf('%.2f', f.tuition) as 'Full Tuition',
                p1.o as 'Payment Plan',
                strftime('%m-%d-%Y', 'now', 'localtime') as 'Statement Date'
            from family as f, prettify as p1
            where f.momefid = $ID and
            (p1.type = 'plan' and p1.i = f.plan);"
echo "</TABLE>
<TABLE class="student info">"
$RUN $PRE "select
            p.firstname || ' ' || p.lastname as 'Student Name',
            p.grade as Grade,
            cm.class as Class,
            pp.o as Day
        from person as p, class_member as cm, prettify as pp
        where p.id = cm.personid and
        p.id in (select personid from family_member where momefid = $ID)
        and (pp.i = cm.day and pp.type = 'dow')
        order by firstname;"
echo "</TABLE>
<TABLE class="payment">"
$RUN $PRE "select 
            strftime('%m-%d-%Y', l.date) as Date,
            printf('%.2f', l.amount) as Amount,
            p1.o as 'Transaction Type',
            l.checknum as 'Check Num',
            l.notes as Notes
        from ledger as l, prettify as p1
        where momefid = $ID and
        (p1.type = 'statement' and p1.i = l.type)
        order by l.id;"
$RUN -html "select
    'Balance' , printf('$%.2f', balance) as Balance
    from balance where momefid = $ID;"
echo "</TABLE><BR>
<TABLE class="payoff">"
$RUN -html "select
'Full Payoff', '$' || printf('%.2f', abs(sum(p.amount) - f.tuition))
    from payment as p, family as f where f.momefid = p.momefid and f.momefid = $ID;"
echo "</TABLE>
</BODY>
</HTML>"
