#!/bin/bash


echo 'This will mark all undeposited payments as deposited.'
echo 'Are you sure?'
echo 'Enter to continue, ctrl+c to quit.'

read

./query "update ledger set depositdate = date('now', 'localtime') where depositdate is null and $WHERE;"
./query "update additional_deposits set depositdate = date('now', 'localtime') where depositdate is null and $WHERE;"
