#!/bin/bash

echo "This will mark all new invoices as sent"
echo "Are you sure?"
echo "Enter to continue, ctrl+c to quit."
read

sqlite3 sjm-2017-2018.sqlite << EOS
update invoices set invoice_date = date('now', 'localtime') where invoice_date is null;
EOS
