#!/bin/bash

sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(email) as Parents from parents;
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(*) as "Student-Classes" from students;
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(distinct(first_name ||" "|| last_name)) as "Students" from students;
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(amount) as Adjustments, sum(amount) as Total from payments where type = 'adjustment';
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(amount) as Invoices, sum(debit) as Total from invoices;
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select count(amount) as Payments, sum(amount) as Total from payments where type != 'adjustment';
EOS
echo
sqlite3 sjm-2017-2018.sqlite << EOS
.mode columns
.headers on
select sum(tuition) as "Total Tuition", printf("%.2f", sum(tuition) - (select sum(amount) from payments)) as "Total Outstanding" from parents;
EOS
