#!/bin/bash

DBFILE="sjsmusic.db"

SQL=""

case "$1" in
    '-n') SQL="select count(id) as 'Unsent Notifications' from notification where sentdate is null and superseded is null";;
    '-i') SQL="select count(id) as 'Unsent Invlices' from invoice where sentdate is null and donotsend is null";;
esac

sqlite3 $DBFILE << EOS
.mode line 
.headers on
$SQL;
EOS
