#!/usr/bin/env perl

use feature 'say';

use warnings;
use strict;

use lib qw/lib/;

use MOME;
use Data::Dumper;

my $service = MOME::google_sheets();

my $spreadsheet = $service->spreadsheet(
    {title => 'Instrumental Music Student Registration 2018-2019 (Responses)'}
);

my $worksheet = $spreadsheet->worksheet({title => 'Form Responses 1'});

my @rows = $worksheet->rows;

# Get my rownames and then ditch the row they are in
my %f = reverse %{$rows[0]->content};
pop @rows;

my @fixed_fields = qw/ first last grade /;
my @ins_fields = qw/ ins years /;

my @out = ();
foreach my $row (@rows) {
    if ($row->content->{$f{testing}}) {
        next;
    }

    my %row = %{$row->content};
    foreach my $sn (1..3) {
        foreach my $in (1..3) {
            my @sfields = map { 's' . $sn . $_ } @fixed_fields;
            my @infields = map { 's' . $sn . $_ . $in } @ins_fields;
            my @fields = (@sfields, @infields);

            if (grep { /\w/ } @row{ @f{@infields} }) {
                push @out, [ map{ split / - / } @row{ @f{@fields} } ];
            } else {
                next;
            }
        }
    }
}

my @out_fields = qw/ first last grade band instrument years /;

my $out_sheet = $service->spreadsheet({title => 'Provisional Student Roster'});
my $o = $out_sheet->worksheet({title => 'Sheet1'});

my $x = 1;
my @title_row = map { { row => 1, col => $x++, input_value => ucfirst($_) } } @out_fields;

$o->batchupdate_cell( @title_row );

my $y = 2;
foreach my $row (@out) {

    # 0:first 1:last 2:grade 3:group 4:instrument 5:experience

    if ($row->[3] eq 'Ukulele') {
        $row->[5] = $row->[4];
        $row->[4] = 'Ukulele';
        $row->[3] = 'Ukulele Ministry';
    }

    $row->[5] = '' unless defined $row->[5];

    if ($row->[3] eq 'Band' and $row->[2] > 5) {
        $row->[3] = 'Advnaced Band';
    }

    my $x = 1;
    my @row = map { { row => $y, col => $x++, input_value => $_ } } $row->@*;
    $o->batchupdate_cell( @row );
    $y++;
}
