#!/usr/bin/env perl

use Modern::Perl '2018';
use DBI;
use Excel::Writer::XLSX;

my $SOURCE = 'responses.csv';
my $OUTFILE = 'Tuition-List.xlsx';
my $DBFILE = 'sjsmusic.db';
my $dbh = DBI->connect("dbi:SQLite:dbname=$DBFILE",'','', { RaiseError => 1 });

my $wb = Excel::Writer::XLSX->new($OUTFILE);
my $norm = $wb->add_format( font => 'Arial', size => 10 );
my $bold = $wb->add_format( font => 'Arial', size => 10, bold => 1 );
my $ws = $wb->add_worksheet();

my $x = 0;
my $y = 0;

$ws->write($x, $y, '2019-2020 Tuition List', $bold);
$x = 1;
$ws->write($x, $y, [ qw/ Tuition ID Family / ], $norm);
$x = 2;

my $student_sth = $dbh->prepare(q{ select firstname, lastname, grade, class, instrument
    from student_roster where momefid = ? order by grade, firstname, instrument });

my $family_sth = $dbh->prepare(q{ select momefid, name from family where
    session = (select id from session where active is not null)
    order by name });

$family_sth->execute();

while ( my @family = $family_sth->fetchrow_array() ) {
    $y = 1;
    $student_sth->execute($family[0]);
    $ws->write($x, $y, \@family, $bold);
    while ( my @student = $student_sth->fetchrow_array() ) {
        $x++; $y = 2;
        $ws->write($x, $y, \@student, $norm);
    }
    $student_sth->finish();
    $x++;
}
